export default {
  card: {
    width: 160,
    height: 224,
    distance: 8,
  },
  cardInStack: {
    width: 200,
    height: 280,
    distance: 8,
  },
  packs: [
    {
      name: 'base',
      label: 'GAME_ROOMS.PACKS.BASE',
      selected: true,
      disabled: true,
      items: [
        {
          name: 'defuse',
          label: 'CARDS.DEFUSE.NAME',
          selected: true,
          disabled: true,
        },
        {
          name: 'exploding-kitten',
          label: 'CARDS.EXPLODING_KITTEN.NAME',
          selected: true,
          disabled: true,
        },
        {
          name: 'attack',
          label: 'CARDS.ATTACK.NAME',
          selected: true,
          disabled: true,
        },
        {
          name: 'shuffle',
          label: 'CARDS.SHUFFLE.NAME',
          selected: true,
          disabled: true,
        },
        {
          name: 'see-the-future',
          label: 'CARDS.SEE_THE_FUTURE.NAME',
          selected: true,
          disabled: true,
        },
        {
          name: 'favor',
          label: 'CARDS.FAVOR.NAME',
          selected: true,
          disabled: true,
        },
        {
          name: 'nope',
          label: 'CARDS.NOPE.NAME',
          selected: true,
          disabled: true,
        },
        {
          name: 'skip',
          label: 'CARDS.SKIP.NAME',
          selected: true,
          disabled: true,
        },
        {
          name: 'beard-cat',
          label: 'CARDS.BEARD_CAT.NAME',
          selected: true,
          disabled: true,
        },
        {
          name: 'burrito-cat',
          label: 'CARDS.BURRITO_CAT.NAME',
          selected: true,
          disabled: true,
        },
        {
          name: 'rainbow-cat',
          label: 'CARDS.RAINBOW_CAT.NAME',
          selected: true,
          disabled: true,
        },
        {
          name: 'potato-cat',
          label: 'CARDS.POTATO_CAT.NAME',
          selected: true,
          disabled: true,
        },
        {
          name: 'watermelon-cat',
          label: 'CARDS.WATERMELON_CAT.NAME',
          selected: true,
          disabled: true,
        },
      ],
    },
    {
      name: 'imploding-kittens',
      label: 'GAME_ROOMS.PACKS.IMPLODING_KITTENS',
      selected: true,
      disabled: false,
      items: [
        {
          name: 'imploding-kitten',
          label: 'CARDS.IMPLODING_KITTEN.NAME',
          selected: true,
          disabled: false,
        },
        {
          name: 'get-lower',
          label: 'CARDS.GET_LOWER.NAME',
          selected: true,
          disabled: false,
        },
        {
          name: 'wild-cat',
          label: 'CARDS.WILD_CAT.NAME',
          selected: true,
          disabled: false,
        },
        {
          name: 'reverse',
          label: 'CARDS.REVERSE.NAME',
          selected: true,
          disabled: false,
        },
        {
          name: 'attack-target',
          label: 'CARDS.ATTACK_TARGET.NAME',
          selected: true,
          disabled: false,
        },
        {
          name: 'change-the-future',
          label: 'CARDS.CHANGE_THE_FUTURE.NAME',
          selected: true,
          disabled: false,
        },
      ],
    },
    {
      name: 'streaking-kittens',
      label: 'GAME_ROOMS.PACKS.STREAKING_KITTENS',
      selected: true,
      disabled: false,
      items: [
        {
          name: 'see-the-future-x5',
          label: 'CARDS.SEE_THE_FUTURE_X5.NAME',
          selected: true,
          disabled: false,
        },
        {
          name: 'change-the-future-x5',
          label: 'CARDS.CHANGE_THE_FUTURE_X5.NAME',
          selected: true,
          disabled: false,
        },
        {
          name: 'swap-top-and-bottom',
          label: 'CARDS.SWAP_TOP_AND_BOTTOM.NAME',
          selected: true,
          disabled: false,
        },
        {
          name: 'freedom',
          label: 'CARDS.FREEDOM.NAME',
          selected: true,
          disabled: false,
        },
        {
          name: 'catomic-bomb',
          label: 'CARDS.CATOMIC_BOMB.NAME',
          selected: true,
          disabled: false,
        },
        {
          name: 'garbage-collector',
          label: 'CARDS.GARBAGE_COLLECTOR.NAME',
          selected: true,
          disabled: false,
        },
        {
          name: 'cat-box',
          label: 'CARDS.CAT_BOX.NAME',
          selected: true,
          disabled: false,
        },
      ],
    },
    {
      name: 'extension-pack-3',
      label: 'GAME_ROOMS.PACKS.EXTENSION_PACK_3',
      selected: true,
      disabled: false,
      items: [
        {
          name: 'swap',
          label: 'CARDS.SWAP.NAME',
          selected: true,
          disabled: false,
        },
      ],
    },
  ],
};
